trigger:
  - main

jobs:
  - job: Chocolatey_test_environment
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - script: |
          cd "Chocolatey test environment on Ubuntu"
          sh setup.sh
        displayName: Sets up the test environment of Chocolatey tests on Ubuntu
