version: 2.1

jobs:
  xcodes:
    parameters:
      xcode_version:
        type: string
        default: ""
    macos:
      xcode: "<< parameters.xcode_version >>"
    steps:
      - checkout
      - run:
          name: "Displays Xcode availables"
          command: "sudo xcode-select -p"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  workflow:
    jobs:
      - xcodes:
          matrix:
            parameters:
              xcode_version: ["13.2.1", "13.1.0", "13.0.0", "12.5.1", "12.4.0", "12.3.0", "12.2.0", "12.1.1", "12.0.1", "11.7.0", "11.6.0", "11.5.0", "11.4.1", "10.3.0"]
