---
version: 2.1

parameters:
  shell:
    type: string
    default: "bash.exe"

executors:
  windows: &my_windows
    machine:
      image: windows-server-2019-vs2019:stable
      resource_class: windows.medium
      shell: bash.exe
  linux: &my_linux
    machine:
      image: ubuntu-2004:202111-02

jobs:
  yamllint:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - run:
          name: "Sets the end of line to be the same whatever the OS is"
          command: "git config --global core.autocrlf false"
      - checkout
      - run:
          name: "Installs the latest version of Yamllint"
          command: "pip install yamllint"
      - run:
          name: "Runs yamllint on all the yaml file of the repository"
          command: "yamllint --strict ."
  black:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - when:
          condition:
            equal: [*my_windows, << parameters.os >>]
          steps:
            - run:
                name: "Installs python3"
                command: choco install python3
      - when:
          condition:
            equal: [*my_linux, << parameters.os >>]
          steps:
            - run:
                name: "Sets python3 as default python to use"
                command: echo "export PATH=/usr/bin:/home/circleci/.local/bin:$PATH" >> ~/.bashrc   # yamllint disable-line rule:line-length
      - run:
          name: "Installs the latest version of Black"
          command: |
            pip install black
      - run:
          name: "Runs black on all the yaml file of the repository"
          command: "black --check ."

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  workflow:
    jobs:
      - yamllint:
          matrix:
            parameters:
              os: [windows, linux]
      - black:
          matrix:
            parameters:
              os: [windows, linux]
