steps:
  - script: |
      pip install yamllint
    displayName: Installs the latest version of yamllint
  - script: |
      yamllint .
    displayName: Runs yamllint on all the yaml file of the repository
