---
name: Python formatter

on: push   # yamllint disable-line rule:truthy

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, macos-12, macos-11, ubuntu-22.04, ubuntu-20.04, windows-2022, windows-2019]  # yamllint disable-line rule:line-length
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          version: "~= 23.3.0"
