name: Xcode versions

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-11, macos-latest, macos-10.15]
        xcode_version: [13.2-beta, 13.1, 13.0, 12.5.1, 12.4, 12.3, 12.2, 12.1.1, 12.1, 12.0.1, 11.7, 11.6, 11.5, 11.4.1, 11.3.1, 11.2.1, 10.3]
        exclude:
          - os: macos-11
            xcode_version: 12.3
          - os: macos-11
            xcode_version: 12.2
          - os: macos-11
            xcode_version: 12.1.1
          - os: macos-11
            xcode_version: 12.1
          - os: macos-11
            xcode_version: 12.0.1
          - os: macos-11
            xcode_version: 11.6
          - os: macos-11
            xcode_version: 11.5
          - os: macos-11
            xcode_version: 11.4.1
          - os: macos-11
            xcode_version: 11.3.1
          - os: macos-11
            xcode_version: 11.2.1
          - os: macos-11
            xcode_version: 10.3
          - os: macos-latest
            xcode_version: 12.3
          - os: macos-latest
            xcode_version: 12.2
          - os: macos-latest
            xcode_version: 12.1.1
          - os: macos-latest
            xcode_version: 12.1
          - os: macos-latest
            xcode_version: 12.0.1
          - os: macos-latest
            xcode_version: 11.6
          - os: macos-latest
            xcode_version: 11.5
          - os: macos-latest
            xcode_version: 11.4.1
          - os: macos-latest
            xcode_version: 11.3.1
          - os: macos-latest
            xcode_version: 11.2.1
          - os: macos-latest
            xcode_version: 10.3
          - os: macos-10.15
            xcode_version: 13.2-beta
          - os: macos-10.15
            xcode_version: 13.1
          - os: macos-10.15
            xcode_version: 13.0
          - os: macos-10.15
            xcode_version: 12.5.1
    runs-on: ${{ matrix.os }}
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '${{ matrix.xcode_version }}'
