---
name: Xcode versions

on: push   # yamllint disable-line rule:truthy

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, macos-12, macos-11]
        xcode_version: [15.0, 14.3.1, 14.2, 14.1, 14.0.1, 13.3.1, 13.2.1, 13.1, 13.0, 12.5.1, 12.4, 11.7]   # yamllint disable-line rule:line-length
        exclude:
          - os: macos-13
            xcode_version: 14.0.1
          - os: macos-13
            xcode_version: 13.4.1
          - os: macos-13
            xcode_version: 13.3.1
          - os: macos-13
            xcode_version: 13.2.1
          - os: macos-13
            xcode_version: 13.1
          - os: macos-13
            xcode_version: 13.0
          - os: macos-13
            xcode_version: 12.5.1
          - os: macos-13
            xcode_version: 12.4
          - os: macos-13
            xcode_version: 11.7
          - os: macos-12
            xcode_version: 15.0
          - os: macos-12
            xcode_version: 14.3.1
          - os: macos-12
            xcode_version: 13.0
          - os: macos-12
            xcode_version: 12.5.1
          - os: macos-12
            xcode_version: 12.4
          - os: macos-12
            xcode_version: 11.7
          - os: macos-11
            xcode_version: 15.0
          - os: macos-11
            xcode_version: 14.3.1
          - os: macos-11
            xcode_version: 14.2
          - os: macos-11
            xcode_version: 14.1
          - os: macos-11
            xcode_version: 14.0.1
          - os: macos-11
            xcode_version: 13.3.1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '${{ matrix.xcode_version }}'
